// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzhpxVAhAdxO4o8D5e6SukzPXjSW8ZbtA',
    appId: '1:936604545219:web:c0b4d9832028ae1b84b276',
    messagingSenderId: '936604545219',
    projectId: 'bmedesign-eeglab',
    authDomain: 'bmedesign-eeglab.firebaseapp.com',
    databaseURL: 'https://bmedesign-eeglab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bmedesign-eeglab.appspot.com',
    measurementId: 'G-ZD69T7CF1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR0O9mMRUMD7OfPvYY6kkJSXJ7Lgy89iI',
    appId: '1:936604545219:android:46f221e92cebe5db84b276',
    messagingSenderId: '936604545219',
    projectId: 'bmedesign-eeglab',
    databaseURL: 'https://bmedesign-eeglab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bmedesign-eeglab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4lnFyMHZTsd7jq11OQIDjWWN_iek0rKg',
    appId: '1:936604545219:ios:1164445701f34a5184b276',
    messagingSenderId: '936604545219',
    projectId: 'bmedesign-eeglab',
    databaseURL: 'https://bmedesign-eeglab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bmedesign-eeglab.appspot.com',
    iosClientId: '936604545219-tq0f57olkfmh9ad0gr4aecn7ssjhu1ir.apps.googleusercontent.com',
    iosBundleId: 'com.diemanh.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4lnFyMHZTsd7jq11OQIDjWWN_iek0rKg',
    appId: '1:936604545219:ios:2244f8c5a115490784b276',
    messagingSenderId: '936604545219',
    projectId: 'bmedesign-eeglab',
    databaseURL: 'https://bmedesign-eeglab-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'bmedesign-eeglab.appspot.com',
    iosClientId: '936604545219-ebgcamuqiid45u8bo119g5jku8gffc6i.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
